source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PLToolsGMaps_Example', :exclusive => true do
  pod 'PLToolsGMaps', :path => '../'
  pod 'GoogleMaps'
end

target 'PLToolsGMaps_Tests', :exclusive => true do
  pod 'PLToolsGMaps', :path => '../'

  
end
